name: octa_solar
description: A professional app for Octa-Solar project
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"  # Updated to allow Dart 3.x

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0  # Updated to latest version
  shared_preferences: ^2.3.2  # Updated to latest version
  cupertino_icons: ^1.0.8  # Updated to latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Updated to latest version

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
